[notification]
background_opacity = 0.66
[osd]
background_opacity = 0.66

[keybinds]
validate = ["return", "kp_enter"]
cancel = ["escape"]
left = ["left"]
right = ["right"]
up = ["up"]
down = ["down"]
tab_next = ["tab"]
tab_previous = ["shift+tab", "iso_left_tab"]

[idle.behavior.lock-and-suspend]
action = "lock_and_suspend"
enabled = true
timeout = 900.0
[idle.behavior.screen-off]
action = "screen_off"
enabled = true
timeout = 660.0

[theme]
builtin = "Rosé Pine"
mode = "auto"
source = "builtin"
[theme.templates]
builtin_ids = [ "ghostty", "hyprland" ]
community_ids = [ "pi-agent" ]

[wallpaper]
directory = "~/Pictures"

[wallpaper.default]
path = "~/Pictures/background.jpg"

[nightlight]
enabled = true

[weather]
enabled = true
refresh_minutes = 60
effects = true

